#+STARTUP: showall
#+STARTUP: lognotestate
#+TAGS:
#+SEQ_TODO: TODO STARTED DONE DEFERRED CANCELLED | WAITING DELEGATED APPT
#+DRAWERS: HIDDEN STATE
#+TITLE: Git/Github mininig tutorial
#+CATEGORY: 
#+PROPERTY: header-args: lang           :varname value
#+PROPERTY: header-args:sqlite          :db /path/to/db  :colnames yes
#+PROPERTY: header-args:R               :results output
#+PROPERTY: header-args:sh              :results output



* Intro

This file is information that I wish I had known when I started doing heavy mining of git.


* Git log

Git log has many, many different options

#+BEGIN_SRC sh :output both
exec 2>&1
git  log  --help  | head -20
:
#+END_SRC

#+begin_example
GIT-LOG(1)                        Git Manual                        GIT-LOG(1)

NAME
       git-log - Show commit logs

SYNOPSIS
       git log [<options>] [<revision range>] [[--] <path>...]

DESCRIPTION
       Shows the commit logs.

       The command takes options applicable to the git rev-list command to
       control what is shown and how, and options applicable to the git diff-*
       commands to control how the changes each commit introduces are shown.

OPTIONS
       --follow
           Continue listing the history of a file beyond renames (works only
           for a single file).

#+end_example




** Default output

#+BEGIN_SRC sh 
git -C  /tmp/jruby log -1 | head
#+END_SRC


#+begin_example
commit 45e17306aa870f25094ebc4956e1b03ba12b24e7
Merge: 0f717cf 92aa13a
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Wed Aug 17 16:13:05 2016 -0500

    Merge pull request #4078 from etehtsea/bump-racc
    
    Bump racc. Fixes #4071
#+end_example




** Some important git log options

| --no-abbbrev |

#+BEGIN_SRC sh 
git -C  /tmp/jruby log -1 --no-abbrev| head
#+END_SRC


#+begin_example
commit 45e17306aa870f25094ebc4956e1b03ba12b24e7
Merge: 0f717cf68d04824bfd5d1c66bcc40012176b15d1 92aa13a6245ee7e1ab94011191bc5bb594a1fd04
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Wed Aug 17 16:13:05 2016 -0500

    Merge pull request #4078 from etehtsea/bump-racc
    
    Bump racc. Fixes #4071
#+end_example


| --oneline    |

#+BEGIN_SRC sh
git -C  /tmp/jruby log --oneline  | head
#+END_SRC


#+begin_example
45e1730 Merge pull request #4078 from etehtsea/bump-racc
0f717cf Merge pull request #4085 from etehtsea/rm-lib-gitignore
9b4164f Remove lib/.gitignore
cc1743c Fixes #3778. Unicode chars in method names aren't accepted
30594f4 Define module_function singleton method as proper clone.
c5028dc Spec for module_function's singleton method with super.
2d5e038 Update to jruby-readline 1.1 snapshot. Fixes #3721
150c83d Use the utility methods, so we can centralize all packed const.
b433c55 Merge pull request #4079 from etehtsea/fix-mailing-lists-link
45ed5f5 Fix link to mailing lists
#+end_example


* Git log can be parsed with a very simple finite state machine

This program will:

- Output the cid in front of any line
- replace any semicolon in the input with <SEMICOLON>

#+name: withCid.pl
#+BEGIN_SRC bash
#!/usr/bin/perl

my $strict;
my $cid;
while (<>) {
    chomp;
    s/;/<SEMICOLON>/g;
    if (/^commit ([0-9a-f]{40}) *(.*)$/) {
        $cid = $1;
        print "$1;$2\n";
    } elsif  (/^([0-9a-f]{40}) *(.*)$/) {
        $cid = $1;
        print "$1;$2\n";
    } else {
        if (/^(\D+):\s+(.*)$/) {
           $_ = "$1;$2";
        }
        print "$cid;$_\n";
    }
}
#+END_SRC

#+BEGIN_SRC sh
git -C /tmp/jruby log -1  | perl withCid.pl 
#+END_SRC


#+begin_example
45e17306aa870f25094ebc4956e1b03ba12b24e7;
45e17306aa870f25094ebc4956e1b03ba12b24e7;Merge;0f717cf 92aa13a
45e17306aa870f25094ebc4956e1b03ba12b24e7;Author;Charles Oliver Nutter <headius@headius.com>
45e17306aa870f25094ebc4956e1b03ba12b24e7;Date;Wed Aug 17 16:13:05 2016 -0500
45e17306aa870f25094ebc4956e1b03ba12b24e7;
45e17306aa870f25094ebc4956e1b03ba12b24e7;    Merge pull request #4078 from etehtsea/bump-racc
45e17306aa870f25094ebc4956e1b03ba12b24e7;    
45e17306aa870f25094ebc4956e1b03ba12b24e7;    Bump racc. Fixes #4071
#+end_example

So now  we can extract any information we want:

#+BEGIN_SRC sh
git -C /tmp/jruby log -6  | perl withCid.pl | grep ';Author;' 
#+END_SRC


#+begin_example
45e17306aa870f25094ebc4956e1b03ba12b24e7;Author;Charles Oliver Nutter <headius@headius.com>
0f717cf68d04824bfd5d1c66bcc40012176b15d1;Author;Charles Oliver Nutter <headius@headius.com>
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444;Author;Konstantin Shabanov <mail@etehtsea.me>
cc1743cb60f9c3898a778f877ab3f4c46666e0ff;Author;Thomas E. Enebo <tom.enebo@gmail.com>
30594f467c2fe9165f263dd38796de5296c5576e;Author;Charles Oliver Nutter <headius@headius.com>
c5028dc54fa9a934273837758bf3040af1bb66a5;Author;Charles Oliver Nutter <headius@headius.com>
#+end_example

or you can learn how to do it via the format option:

#+BEGIN_SRC sh
git -C /tmp/jruby log -6  --format='%H;%an'
#+END_SRC

#+begin_example
45e17306aa870f25094ebc4956e1b03ba12b24e7;Charles Oliver Nutter;Merge pull request #4078 from etehtsea/bump-racc
0f717cf68d04824bfd5d1c66bcc40012176b15d1;Charles Oliver Nutter;Merge pull request #4085 from etehtsea/rm-lib-gitignore
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444;Konstantin Shabanov;Remove lib/.gitignore
cc1743cb60f9c3898a778f877ab3f4c46666e0ff;Thomas E. Enebo;Fixes #3778. Unicode chars in method names aren't accepted
30594f467c2fe9165f263dd38796de5296c5576e;Charles Oliver Nutter;Define module_function singleton method as proper clone.
c5028dc54fa9a934273837758bf3040af1bb66a5;Charles Oliver Nutter;Spec for module_function's singleton method with super.
#+end_example


#+BEGIN_SRC sh
git -C /tmp/jruby log -6  --format='%H;Commiter;%cn; CommiterDate;%ct'
#+END_SRC


#+begin_example
45e17306aa870f25094ebc4956e1b03ba12b24e7;Commiter;GitHub; CommiterDate;1471468385
0f717cf68d04824bfd5d1c66bcc40012176b15d1;Commiter;GitHub; CommiterDate;1471467486
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444;Commiter;Konstantin Shabanov; CommiterDate;1471449551
cc1743cb60f9c3898a778f877ab3f4c46666e0ff;Commiter;Thomas E. Enebo; CommiterDate;1471447247
30594f467c2fe9165f263dd38796de5296c5576e;Commiter;Charles Oliver Nutter; CommiterDate;1471387780
c5028dc54fa9a934273837758bf3040af1bb66a5;Commiter;Charles Oliver Nutter; CommiterDate;1471387712
#+end_example

* You can easily import info into a database

warning. you have to be careful about using separators that might appear in the fields. It is safer to use your own
filter (see my example above). that way  you can make sure the separator is never part of a field.

#+BEGIN_SRC sh
git -C /tmp/jruby log  --format='%H<SEMI>%an<SEMI>%ae<SEMI>%at<SEMI>%cn<SEMI>%ce<SEMI>%ct<SEMI>%s' > /tmp/rip.rip
# replace semicolons with a marker so we can import it
perl -pe 's/;/<SEMICOLON>/g;' /tmp/rip.rip > /tmp/rip.rip2
# replace <SEMI> with the ; delimiter (I like ;)
perl -pe 's/<SEMI>/;/g' /tmp/rip.rip2 > /tmp/rip.rip3
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sqlite :db /tmp/mydb.sql
drop table if exists commits;
create table commits(cid varchar, author varchar, authoremail varchar, authortime int, 
                     committer varchar, commiteremail varchar, commitdate int, summary varchar);
.mode csv commits
.separator ;
.import "/tmp/rip.rip3" commits
select count(*) from commits;
#+END_SRC

| count(*) |
|----------|
|    38575 |



#+BEGIN_SRC sqlite :db /tmp/mydb.sql
select author, authoremail, count(*) from commits group by author, authoremail order by count(*) desc limit 6;
#+END_SRC

| author                | authoremail             | count(*) |
|-----------------------+-------------------------+----------|
| Charles Oliver Nutter | headius@headius.com     |     9390 |
| Chris Seaton          | chris@chrisseaton.com   |     3687 |
| Thomas E. Enebo       | tom.enebo@gmail.com     |     3042 |
| Benoit Daloze         | eregontp@gmail.com      |     2928 |
| Chris Seaton          | chris.seaton@oracle.com |     2166 |
| kares                 | self@kares.org          |     1503 |


#+BEGIN_SRC sqlite :db /tmp/mydb.sql
select cid, summary from commits limit 4;
#+END_SRC

| cid                                      | summary                                                    |
|------------------------------------------+------------------------------------------------------------|
| 45e17306aa870f25094ebc4956e1b03ba12b24e7 | Merge pull request #4078 from etehtsea/bump-racc           |
| 0f717cf68d04824bfd5d1c66bcc40012176b15d1 | Merge pull request #4085 from etehtsea/rm-lib-gitignore    |
| 9b4164f7c73247c1fd3c5e2e817d2d58bc56c444 | Remove lib/.gitignore                                      |
| cc1743cb60f9c3898a778f877ab3f4c46666e0ff | Fixes #3778. Unicode chars in method names aren't accepted |


* Branches

When cloning, by default, you only get one branch

See [[http://github.com/dmgerman/xournal]]


#+BEGIN_SRC 
cd /tmp/
git clone http://github.com/dmgerman/xournal 
#+END_SRC

#+BEGIN_SRC sh
git -C /tmp/xournal branch
#+END_SRC


#+begin_example
* master
#+end_example

You must fetch everything

#+BEGIN_SRC sh
git -C /tmp/xournal fetch --all
#+END_SRC

Then you have a file: .git/FETCH_HEAD that contains all information of branches

#+BEGIN_SRC sh
cat /tmp/xournal/.git/FETCH_HEAD
#+END_SRC


#+begin_example
03b7651644aea0a95fd09f1566d4a667df8d7950		branch 'master' of http://github.com/dmgerman/xournal
aaa50b9cc7efadea40bc812cd3dfb08d446b79a2	not-for-merge	branch 'a5paper' of http://github.com/dmgerman/xournal
b8e7c5036289fbe36d423c4db9ce7a63bd1c6f75	not-for-merge	branch 'ahmed' of http://github.com/dmgerman/xournal
b3f07476632ed5b742af3506cb7cd4272956d339	not-for-merge	branch 'bookmarks' of http://github.com/dmgerman/xournal
dad5c6c5756e1d47fed8203b606907efab2b17fa	not-for-merge	branch 'cl-options' of http://github.com/dmgerman/xournal
db66cd33599d4d838f4feef5980ba907911bc9e6	not-for-merge	branch 'cmake' of http://github.com/dmgerman/xournal
3b3cb888333d165fe2dd05dfd10560f40ca7befa	not-for-merge	branch 'dmgwin' of http://github.com/dmgerman/xournal
a4d7604766d71790a495acc67a74d8a3cb0de7d4	not-for-merge	branch 'dot-paper-style' of http://github.com/dmgerman/xournal
02afa27473d7907aa64e066a0d6a1394f5f9414a	not-for-merge	branch 'fix-update-width' of http://github.com/dmgerman/xournal
e50be735d47e41739b283298d05b86d2278f5742	not-for-merge	branch 'fix-windows-paths' of http://github.com/dmgerman/xournal
2190827a1818ac313cc3700f8cc94ecec5a00359	not-for-merge	branch 'glade' of http://github.com/dmgerman/xournal
953b0e1fe2f1b5c3e02aa90085144a45f4483f74	not-for-merge	branch 'gtk3' of http://github.com/dmgerman/xournal
9d9e155886255687d9ca882a8e7df3031c450248	not-for-merge	branch 'horizontal-scroll-lock' of http://github.com/dmgerman/xournal
ecd8b62f9c0268d43aeaba762e8f0f04619cae87	not-for-merge	branch 'layers' of http://github.com/dmgerman/xournal
36bad42fc8d20b05647c29219828eacf6b2c1090	not-for-merge	branch 'message' of http://github.com/dmgerman/xournal
69749f060959c32009c13f51f25f4cfdcdb3da8b	not-for-merge	branch 'mru' of http://github.com/dmgerman/xournal
c08da1d700a818cada297aee949b40da780b536e	not-for-merge	branch 'next' of http://github.com/dmgerman/xournal
7481181564eba893b82766a2c34fd785ff07158e	not-for-merge	branch 'popupmenu' of http://github.com/dmgerman/xournal
f68880c6aef5d3f4b9e62d58e38bec2dbbe6a36b	not-for-merge	branch 'quick-zoom' of http://github.com/dmgerman/xournal
a8b50c33e6ec0c63002b6b7feba05fe2ab433af9	not-for-merge	branch 'redo' of http://github.com/dmgerman/xournal
ca3bc5b770ee0b1ada9447969f48ca25c7443d32	not-for-merge	branch 'snap-to-grid' of http://github.com/dmgerman/xournal
af7c91dc621677ec03c65c11814418d36585c3c2	not-for-merge	branch 'touchscreen-as-hand-tool' of http://github.com/dmgerman/xournal
f28489f7f7477e59a9015e17a795c88ab89d977d	not-for-merge	branch 'upstream' of http://github.com/dmgerman/xournal
#+end_example

By default, git log gives you the log of the "current" branch

#+BEGIN_SRC sh
git -C /tmp/xournal log  -1
#+END_SRC


#+begin_example
commit 03b7651644aea0a95fd09f1566d4a667df8d7950
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:36 2016 +0200

    update readme.org
#+end_example

but git log --glob='*' gives you _all_ commits


#+BEGIN_SRC sh
git -C /tmp/xournal log --glob='*' -2
#+END_SRC


#+begin_example
commit c08da1d700a818cada297aee949b40da780b536e
Merge: 661075a 03b7651
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:46 2016 +0200

    Merge branch 'master' into next

commit 03b7651644aea0a95fd09f1566d4a667df8d7950
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:36 2016 +0200

    update readme.org
#+end_example

or a specific branch: use origin to indicate that it is the branch upstream

#+BEGIN_SRC sh
git -C /tmp/xournal log origin/mru -2
#+END_SRC


#+begin_example
commit 69749f060959c32009c13f51f25f4cfdcdb3da8b
Author: Daniel M German <dmg@uvic.ca>
Date:   Tue Dec 9 20:57:42 2014 -0800

    Support for page numbers in Most recently used files.
    
    - The current page is saved in the .xoj file
    - Under Linux, it is also saved in the gvfs metadata. Precendece is file current page, then gvfs metadata.

commit f28489f7f7477e59a9015e17a795c88ab89d977d
Author: Denis Auroux <auroux@users.sourceforge.net>
Date:   Tue Apr 5 14:51:54 2016 -0700

    text and image tools activate on button release instead of button press, to avoid subsequent confusion between clicks in toolbar and drawing area
#+end_example

* Parents

The DAG is the fundamental data structure of git

- Every commit has zero or more parents
- Merges have two or more parents (I have seen 16 parents in one commit)
- Current heads of branches (including master) might have zero children (at least on branch will always have zero children)
- Roots of the branches have zero parents 

#+BEGIN_SRC sh
git -C /tmp/xournal log --pretty='%H;%P' -n 5 origin/next
#+END_SRC


#+begin_example
c08da1d700a818cada297aee949b40da780b536e;661075ab91e296fb5b702be379967bd581290942 03b7651644aea0a95fd09f1566d4a667df8d7950
03b7651644aea0a95fd09f1566d4a667df8d7950;addb9bf2c0be2ff61e72d3c565253d319311d2f8
661075ab91e296fb5b702be379967bd581290942;ae37e72839ae59308974b9375eae0c8630c4795c addb9bf2c0be2ff61e72d3c565253d319311d2f8
ae37e72839ae59308974b9375eae0c8630c4795c;a40e13ec95dc9b8fbc1578ec5be8cbce6e7c839c f28489f7f7477e59a9015e17a795c88ab89d977d
addb9bf2c0be2ff61e72d3c565253d319311d2f8;f28489f7f7477e59a9015e17a795c88ab89d977d
#+end_example


** Roots:

- there might be more than one root (linux has 4, git has more)
- commits without parents

** Merges

- You can ask for only merges

#+BEGIN_SRC sh
git -C /tmp/xournal log --merges -5 --glob='*' --pretty='%H;%P'
#+END_SRC


#+begin_example
c08da1d700a818cada297aee949b40da780b536e;661075ab91e296fb5b702be379967bd581290942 03b7651644aea0a95fd09f1566d4a667df8d7950
661075ab91e296fb5b702be379967bd581290942;ae37e72839ae59308974b9375eae0c8630c4795c addb9bf2c0be2ff61e72d3c565253d319311d2f8
ae37e72839ae59308974b9375eae0c8630c4795c;a40e13ec95dc9b8fbc1578ec5be8cbce6e7c839c f28489f7f7477e59a9015e17a795c88ab89d977d
69d03075893cd69390b58f25d9c94390302e87f3;ceef9524bc5be69c1ae26985f47cbd96d49066cf 37ab0d2142fcd605047480e4c838a463691ef067
ceef9524bc5be69c1ae26985f47cbd96d49066cf;59c4b8f96d0d5ab9b26324976358ec4fbfa255eb c10f6e8d0793a40bd6e19fad861194bd40b0ffec
#+end_example

#+BEGIN_SRC sh
git -C /tmp/xournal log --pretty='%H;%P' | tail -5
#+END_SRC


#+begin_example
bdd9b21324587503275e285acdf9ba19c82d83b8;bcdd3a0382ffaa7fb9e117500403a6360b2ef5b2
bcdd3a0382ffaa7fb9e117500403a6360b2ef5b2;1aaa40619a8afc55fdd4d6fe4f883aa0cf237bd3
1aaa40619a8afc55fdd4d6fe4f883aa0cf237bd3;48d831491f93ea65d3fe9c27933ba33c3e303295
48d831491f93ea65d3fe9c27933ba33c3e303295;9d02cbbbc188127f49e59daa56f783db1312e53d
9d02cbbbc188127f49e59daa56f783db1312e53d;
#+end_example


* Files modified: do not use --numstat, and never _ever_ think of using --stat

- There are several ways to get the files modified in a commit

#+BEGIN_SRC sh
git  -C /tmp/xournal log -5 --numstat 
#+END_SRC


#+begin_example
commit 03b7651644aea0a95fd09f1566d4a667df8d7950
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:36 2016 +0200

    update readme.org

26	21	README.org

commit addb9bf2c0be2ff61e72d3c565253d319311d2f8
Author: dmg <dmg@uvic.ca>
Date:   Sat Nov 23 10:59:37 2013 +0900

    Added readme.org to distinguish this repo from upstream

128	0	README.org

commit f28489f7f7477e59a9015e17a795c88ab89d977d
Author: Denis Auroux <auroux@users.sourceforge.net>
Date:   Tue Apr 5 14:51:54 2016 -0700

    text and image tools activate on button release instead of button press, to avoid subsequent confusion between clicks in toolbar and drawing area

5	1	ChangeLog
16	2	src/xo-callbacks.c
2	0	src/xournal.h

commit 1b6ef5a24461b72bf2e98f1bfaad3567f0b9f542
Author: Denis Auroux <auroux@users.sourceforge.net>
Date:   Thu Dec 3 12:24:17 2015 -0800

    Allow input coordinates greater than a million pixels (bug #166)

1	1	src/xo-misc.c

commit c10f6e8d0793a40bd6e19fad861194bd40b0ffec
Author: Denis Auroux <auroux@users.sourceforge.net>
Date:   Sat Oct 24 21:35:11 2015 -0700

    Look for toolbar pixmaps first in configured install directory and then near
    argv[0], instead of the other way around (bug #164)

3	3	src/main.c
#+end_example

Several issues:

- it does not indicate if the file is added or removed
- it does not output anything for binary files
- Time consuming:
  - A simple test: git log -100000 (log of 10k commits) of the linux kernel
  - --numstat and stat 66 seconds
  - --raw (see below): 10 seconds

** Better solution: --raw

#+BEGIN_SRC sh
git  -C /tmp/xournal log -3 --no-abbrev --raw 
#+END_SRC


#+begin_example
commit 03b7651644aea0a95fd09f1566d4a667df8d7950
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:36 2016 +0200

    update readme.org

:100644 100644 8b69815b87e05a3cdcc77c4f6248f9703f8c108f 7f2fe5eed121663f434adbea6d292e35471330f5 M	README.org

commit addb9bf2c0be2ff61e72d3c565253d319311d2f8
Author: dmg <dmg@uvic.ca>
Date:   Sat Nov 23 10:59:37 2013 +0900

    Added readme.org to distinguish this repo from upstream

:000000 100644 0000000000000000000000000000000000000000 8b69815b87e05a3cdcc77c4f6248f9703f8c108f A	README.org

commit f28489f7f7477e59a9015e17a795c88ab89d977d
Author: Denis Auroux <auroux@users.sourceforge.net>
Date:   Tue Apr 5 14:51:54 2016 -0700

    text and image tools activate on button release instead of button press, to avoid subsequent confusion between clicks in toolbar and drawing area

:100644 100644 313f6609b13e5fe968e9d3394cb7de4585d6625b bd538e19ff86040d9f84ee369d511f8b41042311 M	ChangeLog
:100644 100644 95fc7ddc2a6127f0c9f84bfab60babc1852d02bb 128078fb76e9c246a9199a6f33dbf4600f266590 M	src/xo-callbacks.c
:100644 100644 044385738b2f0372959e74738e4566a7323a9f30 66e685007e17d9c7305ec56cf7272dc376fd35e6 M	src/xournal.h
#+end_example


** format

#+BEGIN_EXAMPLE
:100644 100644 313f6609b13e5fe968e9d3394cb7de4585d6625b bd538e19ff86040d9f84ee369d511f8b41042311 M	ChangeLog
:100644 100644 95fc7ddc2a6127f0c9f84bfab60babc1852d02bjb 128078fb76e9c246a9199a6f33dbf4600f266590 M	src/xo-callbacks.c
:100644 100644 044385738b2f0372959e74738e4566a7323a9f30 66e685007e17d9c7305ec56cf7272dc376fd35e6 M	src/xournal.h
#+END_EXAMPLE

| File mode before |                                          |
| File mode after  |                                          |
| blob before      |                                          |
| blob after       |                                          |
| operation        | M modified, D deleted, R rename, A added |
| filename         |                                          |

For merges, it contains n+1 info:

- File info before in each branch
- File info after merge

but only when the merge included a patch

** --name-status

- Easier to parse
- but it does not track renames (files appear deleted and added)

#+BEGIN_SRC sh
git  -C /tmp/jruby log --oneline --no-abbrev --name-status -5
#+END_SRC

#+begin_example
45e17306aa870f25094ebc4956e1b03ba12b24e7 Merge pull request #4078 from etehtsea/bump-racc
0f717cf68d04824bfd5d1c66bcc40012176b15d1 Merge pull request #4085 from etehtsea/rm-lib-gitignore
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444 Remove lib/.gitignore
M	.gitignore
D	lib/.gitignore
cc1743cb60f9c3898a778f877ab3f4c46666e0ff Fixes #3778. Unicode chars in method names aren't accepted
M	core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
M	core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
30594f467c2fe9165f263dd38796de5296c5576e Define module_function singleton method as proper clone.
M	core/src/main/java/org/jruby/runtime/Helpers.java
#+end_example

You can now easily preprocess the data to load it into our database

#+BEGIN_SRC sh
git  -C /tmp/jruby log --oneline --no-abbrev --name-status -10 | perl withCid.pl  | egrep $';.\t'  | perl -pe 's/\t/;/'
#+END_SRC

#+begin_example
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444;M;.gitignore
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444;D;lib/.gitignore
cc1743cb60f9c3898a778f877ab3f4c46666e0ff;M;core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
cc1743cb60f9c3898a778f877ab3f4c46666e0ff;M;core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
30594f467c2fe9165f263dd38796de5296c5576e;M;core/src/main/java/org/jruby/runtime/Helpers.java
c5028dc54fa9a934273837758bf3040af1bb66a5;M;spec/ruby/core/module/module_function_spec.rb
2d5e038c692ec8b913c8b21197bad9b9f0d73772;M;lib/pom.rb
2d5e038c692ec8b913c8b21197bad9b9f0d73772;M;lib/pom.xml
150c83d5cdd1b39b2802d74ff0b692db3f95fbc5;M;core/src/main/java/org/jruby/RubyArray.java
45ed5f5af5b47e4039341275b538ac4015b71778;M;pom.rb
45ed5f5af5b47e4039341275b538ac4015b71778;M;pom.xml
#+end_example



* Extracting versions of files

- Git stores the actual contents of the files: the blobs
- *do not extract using git checkout*. it is very slow
- The --raw gives you the blob of a given file


#+BEGIN_SRC sh
git  -C /tmp/xournal log -1 --no-abbrev --raw 
#+END_SRC


#+begin_example
commit 03b7651644aea0a95fd09f1566d4a667df8d7950
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:36 2016 +0200

    update readme.org

:100644 100644 8b69815b87e05a3cdcc77c4f6248f9703f8c108f 7f2fe5eed121663f434adbea6d292e35471330f5 M	README.org
#+end_example

You can extract the contents of file in two ways: 

** by cid:filename

#+BEGIN_SRC sh
git -C /tmp/xournal show 03b7651644aea0a95fd09f1566d4a667df8d7950:README.org | head
#+END_SRC


#+begin_example
#+STARTUP: showall

* This is a testing repository for new features of Xournal

This is a mirror of the git repository of Xournal
(http://xournal.sourceforge.net) and contains experimental code that
is not yet in the official repo. Its purpose is to help in the
development of new features

It should *not be used* for code intended for further distribution.
#+end_example

** by blob

#+BEGIN_SRC sh
git -C /tmp/xournal show 7f2fe5eed121663f434adbea6d292e35471330f5 | head
#+END_SRC


#+begin_example
#+STARTUP: showall

* This is a testing repository for new features of Xournal

This is a mirror of the git repository of Xournal
(http://xournal.sourceforge.net) and contains experimental code that
is not yet in the official repo. Its purpose is to help in the
development of new features

It should *not be used* for code intended for further distribution.
#+end_example

** How the blob id is computed:

- Concatenate: 
  - "blob "
  - ASCII length of the file
  - ASCII 0
  - Contents

#+BEGIN_SRC perl :results output
use Digest::SHA qw(sha1_hex);

$file = "README.org";
chdir("/tmp/xournal");

#read contents of file
local $/;
open(IN, $file);
$contents = <IN>;
close IN;


$len = length($contents);
print sha1_hex("blob $len\0$contents");
#+END_SRC


#+begin_example
7f2fe5eed121663f434adbea6d292e35471330f5
#+end_example

#+BEGIN_SRC sh
git -C /tmp/xournal  log --no-abbrev -1 --raw README.org 
#+END_SRC


#+begin_example
commit 03b7651644aea0a95fd09f1566d4a667df8d7950
Author: D German <dmg@uvic.ca>
Date:   Wed Apr 20 11:04:36 2016 +0200

    update readme.org

:100644 100644 8b69815b87e05a3cdcc77c4f6248f9703f8c108f 7f2fe5eed121663f434adbea6d292e35471330f5 M	README.org
#+end_example


* What about who has modified a given file?

git blame

#+BEGIN_SRC sh
git -C /tmp/xournal blame src/xo-file.c | head
#+END_SRC


#+begin_example
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    1) /*
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    2)  *  This program is free software; you can redistribute it and/or
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    3)  *  modify it under the terms of the GNU General Public
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    4)  *  License as published by the Free Software Foundation; either
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    5)  *  version 2 of the License, or (at your option) any later version.
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    6)  *
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    7)  *  This software is distributed in the hope that it will be useful,
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    8)  *  but WITHOUT ANY WARRANTY; without even the implied warranty of  
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000    9)  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
a71d7685 (Denis Auroux 2012-05-22 19:06:49 +0000   10)  *  General Public License for more details.
#+end_example

the format is not very nice

| time     | unix time in epoch                                               |
| summary  | one liner of commit log                                          |
| filename | if file was renamed, it tells you what the original filename was |
| \tab     | actual content is preceeded by tab                               |

It is also dangerous to use:

- The authors are mapped using the file .mailmap found in the root directory of the project

#+BEGIN_SRC 
#
# This list is used by git-shortlog to fix a few botched name translations
# in the git archive, either because the author's full name was messed up
# and/or not always written the same way, making contributions from the
# same person appearing not to be so or badly displayed.
#
# repo-abbrev: /pub/scm/linux/kernel/git/
#
Boris Brezillon <boris.brezillon@free-electrons.com> <b.brezillon.dev@gmail.com>
James Bottomley <jejb@mulgrave.(none)>
James Bottomley <jejb@titanic.il.steeleye.com>
James E Wilson <wilson@specifix.com>
James Ketrenos <jketreno@io.(none)>
<javier@osg.samsung.com> <javier.martinez@collabora.co.uk>
#+END_SRC

#+BEGIN_SRC sh
git -C /tmp/jruby log -6  --format='%H;author;%an;mailmapAuthor;%aN'
#+END_SRC


#+begin_example
45e17306aa870f25094ebc4956e1b03ba12b24e7;author;Charles Oliver Nutter;mailmapAuthor;Charles Oliver Nutter
0f717cf68d04824bfd5d1c66bcc40012176b15d1;author;Charles Oliver Nutter;mailmapAuthor;Charles Oliver Nutter
9b4164f7c73247c1fd3c5e2e817d2d58bc56c444;author;Konstantin Shabanov;mailmapAuthor;Konstantin Shabanov
cc1743cb60f9c3898a778f877ab3f4c46666e0ff;author;Thomas E. Enebo;mailmapAuthor;Thomas E. Enebo
30594f467c2fe9165f263dd38796de5296c5576e;author;Charles Oliver Nutter;mailmapAuthor;Charles Oliver Nutter
c5028dc54fa9a934273837758bf3040af1bb66a5;author;Charles Oliver Nutter;mailmapAuthor;Charles Oliver Nutter
#+end_example


Another alternative: use porcelain (you also get the previous commit id for every line)

#+BEGIN_SRC sh
git -C /tmp/xournal blame --no-abbrev src/xo-file.c --line-porcelain | head -26
#+END_SRC


#+begin_example
a71d76854d1caabd6bcc7fd1ce6a105fca06de61 1 1 15
author Denis Auroux
author-mail <auroux@math.berkeley.edu>
author-time 1337713609
author-tz +0000
committer Denis Auroux
committer-mail <auroux@math.berkeley.edu>
committer-time 1337713609
committer-tz +0000
summary Add "GPL v2 or later" headers to the source files
previous c6c08ac049e4d849ca96363d8feba52c0cb8474a src/xo-file.c
filename src/xo-file.c
	/*
a71d76854d1caabd6bcc7fd1ce6a105fca06de61 2 2
author Denis Auroux
author-mail <auroux@math.berkeley.edu>
author-time 1337713609
author-tz +0000
committer Denis Auroux
committer-mail <auroux@math.berkeley.edu>
committer-time 1337713609
committer-tz +0000
summary Add "GPL v2 or later" headers to the source files
previous c6c08ac049e4d849ca96363d8feba52c0cb8474a src/xo-file.c
filename src/xo-file.c
	 *  This program is free software; you can redistribute it and/or
#+end_example


* Many commands have porcelain output

- They make your processing easier

* Final comments

- Read the man pages
- You can simplify your life by asking for the right info 

